wandb_version: 1

nn_architecture:
  desc: null
  value:
  - 75
  - 128
  - 128
  - 50
activation_function:
  desc: null
  value: Tanh
num_generations:
  desc: null
  value: 70
es_popsize:
  desc: null
  value: 6912
_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1707236877.613693
    t:
      1:
      - 12
      - 45
      - 55
      2:
      - 12
      - 45
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.11.7
      5: 0.16.2
      8:
      - 1
      - 5
      13: linux-x86_64
