 experiment:
   interface: 'HPC' # HPC or VSC 
   run_name_format: "{notes} {reward_type} arms {arm_setup} popsize {es_popsize} {cost_expr} {fitness_expr}" # put an f in front in .py script
 wandb:
   project: "biomimicry"
   group: "cost_fitness"
   tags: ["no_cost", "reward"]
   notes: "b01_r01"
 morphology:
   arm_setup: [ 7, 7, 7, 7, 7 ]
   joint_control: 'position'
 arena:
   arena_size: !!python/tuple [ 10, 10 ]
   sand_ground_color: False
 environment:
   reward_type: 'distance' # choose from distance, target or light
   sensor_selection: !!python/tuple [ 'joint_position', 'joint_actuator_force', 'segment_contact']
   num_physics_steps_per_control_step: 10
   simulation_time: 5
   joint_randomization_noise_scale: 0.0
   light_perlin_noise_scale: 4
   target_distance: 3
   target_position: [ 8., 0., 0.]
   color_contacts: False
 damage:
   damage: False
   arm_setup_damage: [ 5, 0, 0, 0, 0]
 evolution:
   es_popsize: 6912
   num_generations: 70
   cost_expr: "no_cost" # choose from ["no_cost", "torque*ang_vel", "torque"]
   fitness_expr: "reward" # choose from ["reward", "reward/cost", "reward+reward/cost"]
 controller:
   hidden_layers: [ 128, 128 ]
 
