 experiment:
   interface: 'VSC' # HPC or VSC 
   run_name_format: "{reward_type} arms {arm_setup} popsize {es_popsize} {notes}" 
 wandb:
   project: "job_sub_test"
   group: "Local_VSC"
   tags: ["something", "something_else"]
   notes: "Additional modules"
 morphology:
   arm_setup: [ 5, 0, 5, 0, 0 ]
   joint_control: 'position'
 arena:
   arena_size: !!python/tuple [ 10, 5 ]
   sand_ground_color: False
 environment:
   reward_type: 'distance' # choose from distance, target or light
   sensor_selection: !!python/tuple [ 'joint_position', 'joint_actuator_force', 'segment_contact']
   num_physics_steps_per_control_step: 10
   simulation_time: 5
   joint_randomization_noise_scale: 0.0
   light_perlin_noise_scale: 4
   target_distance: 9
   target_position: [ 9., 0., 0.]
   color_contacts: False
 damage:
   damage: True
   arm_setup_damage: [ 5, 0, 0, 0, 0]
 evolution:
   es_popsize: 2
   num_generations: 10
   fitness:
   cost_expr: "nocost" # choose from ["nocost", "torque x angvel", "torque"]
   fitness_expr: "reward" # choose from ["reward", "reward _ cost", "reward + reward _ cost"]
 controller:
   hidden_layers: [ 128, 128 ]
 
