wandb_version: 1

nn_architecture:
  desc: null
  value:
  - 312
  - 128
  - 128
  - 100
arm_setup:
  desc: null
  value:
  - 10
  - 10
  - 10
  - 10
  - 10
num_params:
  desc: null
  value: 69476
activation_function:
  desc: null
  value: Tanh
num_generations:
  desc: null
  value: 150
es_popsize:
  desc: null
  value: 400
_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1707260385.576376
    t:
      1:
      - 12
      - 45
      - 55
      2:
      - 12
      - 45
      - 55
      3:
      - 16
      - 23
      4: 3.11.7
      5: 0.16.2
      8:
      - 1
      - 5
      13: linux-x86_64
